AWSTemplateFormatVersion: 2010-09-09
Description: >
     This AWS CloudFormation stack will create the Security Groups:
     AUTHOR: Venkat Yarlagadda
Parameters:
  SGName:
         Description: SGName to create Security Group
         Type: String
  VPC:
         Type: AWS::EC2::VPC::Id
         Description: Choose which VPC the Security Group should be deployed to
  AnsibleSecurityGroup:
         Description: Select the Security Group to access the EC2 Instance from Ansible Server
         Type: AWS::EC2::SecurityGroup::Id
Resources:
  SG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VPC
      GroupDescription:  !Ref SGName
      GroupName: !Ref SGName
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref AnsibleSecurityGroup

      Tags:
        - Key: Name
          Value: !Ref SGName
